"""Add image_path to Teachers

Revision ID: add_image_path_to_teachers
Revises: 
Create Date: 2025-07-13 11:35:00.000000

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'add_image_path_to_teachers'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Teachers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_path', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Teachers', schema=None) as batch_op:
        batch_op.drop_column('image_path')
    # ### end Alembic commands ###
